# Generated by Django 5.0 on 2023-12-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="UserCardModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_option",
                    models.CharField(
                        choices=[
                            ("media/aliens.jpg", "Alien"),
                            ("media/batman.jpg", "Batman"),
                            ("media/joker.jpg", "Joker"),
                            ("media/madmax.jpg", "Mad Max"),
                            ("media/predator.jpg", "Predator"),
                        ],
                        default="media/aliens.jpg",
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("job_title", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
