# Generated by Django 5.0 on 2023-12-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("namecards", "0002_delete_testmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercardmodel",
            name="image_option",
            field=models.CharField(
                choices=[
                    ("media/aliens.jpeg", "Alien"),
                    ("media/batman.jpeg", "Batman"),
                    ("media/joker.jpeg", "Joker"),
                    ("media/madmax.jpeg", "Mad Max"),
                    ("media/predator.jpeg", "Predator"),
                ],
                default="media/aliens.jpg",
                max_length=100,
            ),
        ),
    ]
