# Generated by Django 5.0 on 2023-12-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("namecards", "0004_alter_usercardmodel_image_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercardmodel",
            name="image_option",
            field=models.CharField(
                choices=[
                    ("media/aliens.jpeg", "Alien"),
                    ("media/batman.jpeg", "Batman"),
                    ("media/joker.jpeg", "Joker"),
                    ("media/madmax.jpeg", "Mad Max"),
                    ("media/predator.jpeg", "Predator"),
                    ("media/demogorgon.jpeg", "Demogorgon"),
                    ("media/golam.jpeg", "Golam"),
                    ("media/robocop.jpeg", "Robotzsaru"),
                    ("media/terminator.jpeg", "Terminator"),
                ],
                default="media/aliens.jpeg",
                max_length=100,
            ),
        ),
    ]
